from neoramon/ubuntu:16.04

RUN sudo apt-get update
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
#RUN sudo apt-get install npm=3.5.2-0ubuntu4 -y

CMD /bin/bash