spring:
  application:
    name: person
  datasource:
    continue-on-error: true

  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    serviceUrl:
#      defaultZone: http://172.17.0.2:8081/eureka/
      defaultZone: http://eureka:8081/eureka/
  instance:
    hostname: person_service
    nonSecurePort: 8081